# Generated by Django 5.2.17 on 2026-09-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. "LAG-IKD"', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g. "Ikorodu Axis"', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_restricted', models.BooleanField(default=False, help_text='Alcohol and other restricted lines may be delivered here')),
                ('cod_allowed', models.BooleanField(default=False, help_text='Cash on delivery permitted')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'delivery_zone',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Standard', max_length=100)),
                ('rate_type', models.CharField(choices=[('flat', 'Flat fee'), ('weight', 'By weight'), ('order_value', 'By order value'), ('free', 'Free')], default='flat', max_length=16)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('per_kg_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('free_above_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estimated_days_min', models.SmallIntegerField(blank=True, null=True)),
                ('estimated_days_max', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='delivery.deliveryzone')),
            ],
            options={
                'db_table': 'delivery_rate',
                'ordering': ['zone', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZoneArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('city', 'City'), ('state', 'State'), ('postal', 'Postal code'), ('lga', 'Local government area')], max_length=16)),
                ('match_value', models.CharField(max_length=120)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='delivery.deliveryzone')),
            ],
            options={
                'db_table': 'delivery_zone_area',
                'constraints': [models.UniqueConstraint(fields=('zone', 'match_type', 'match_value'), name='uq_dza')],
            },
        ),
    ]
