# Generated by Django 5.2.17 on 2026-09-08 18:52

import d2r.accounts.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('priority', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'customer_group',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('admin', 'Administrator'), ('catalogue', 'Catalogue'), ('inventory', 'Inventory'), ('ops', 'Operations'), ('finance', 'Finance'), ('support', 'Customer support'), ('sales', 'Sales')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='Cannot be deleted')),
            ],
            options={
                'db_table': 'staff_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], db_index=True, default='customer', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Django admin access')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('failed_login_count', models.SmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('mfa_secret', models.CharField(blank=True, max_length=64)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', d2r.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('refresh', 'Refresh'), ('password_reset', 'Password reset'), ('email_verify', 'Email verification'), ('otp', 'One-time passcode')], max_length=24)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('rotated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations', to='accounts.authtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_token',
            },
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('account_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('business_name', models.CharField(db_index=True, max_length=200)),
                ('business_type', models.CharField(choices=[('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('supermarket', 'Supermarket'), ('chain', 'Chain store'), ('open_market', 'Open market'), ('neighbourhood', 'Neighbourhood store'), ('other', 'Other')], max_length=32)),
                ('registration_number', models.CharField(blank=True, help_text='CAC number', max_length=64)),
                ('tax_id', models.CharField(blank=True, help_text='TIN', max_length=64)),
                ('primary_contact_name', models.CharField(max_length=150)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('can_view_prices', models.BooleanField(default=False)),
                ('can_order', models.BooleanField(default=False)),
                ('restricted_products_allowed', models.BooleanField(default=False, help_text='Eligible to buy alcohol and other restricted lines')),
                ('cod_allowed', models.BooleanField(default=False, help_text='May pay cash on delivery')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_terms_days', models.SmallIntegerField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Staff only — never shown to the customer')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accounts', to=settings.AUTH_USER_MODEL)),
                ('assigned_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_accounts', to=settings.AUTH_USER_MODEL)),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='delivery.deliveryzone')),
                ('customer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.customergroup')),
            ],
            options={
                'db_table': 'business_account',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('label', models.CharField(blank=True, help_text='e.g. "Ikorodu shop"', max_length=60)),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('delivery', 'Delivery'), ('both', 'Billing and delivery')], default='delivery', max_length=16)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=32)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='NG', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('is_default_delivery', models.BooleanField(default=False)),
                ('delivery_zone', models.ForeignKey(blank=True, help_text='Resolved on save from city/state', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='delivery.deliveryzone')),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.businessaccount')),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='BusinessAccountMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('buyer', 'Buyer'), ('viewer', 'Viewer')], default='buyer', max_length=16)),
                ('is_default', models.BooleanField(default=False, help_text="The user's active account")),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.businessaccount')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_account_member',
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.staffrole')),
            ],
            options={
                'db_table': 'staff_assignment',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active'], name='idx_user_type_active'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['user', 'purpose'], name='idx_token_user_purpose'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_billing', True)), fields=('business_account',), name='uq_addr_default_billing'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_delivery', True)), fields=('business_account',), name='uq_addr_default_delivery'),
        ),
        migrations.AddIndex(
            model_name='businessaccountmember',
            index=models.Index(fields=['user'], name='idx_bam_user'),
        ),
        migrations.AddConstraint(
            model_name='businessaccountmember',
            constraint=models.UniqueConstraint(fields=('business_account', 'user'), name='uq_bam'),
        ),
        migrations.AddIndex(
            model_name='businessaccount',
            index=models.Index(fields=['status'], name='idx_ba_status'),
        ),
        migrations.AddIndex(
            model_name='businessaccount',
            index=models.Index(fields=['customer_group'], name='idx_ba_group'),
        ),
        migrations.AddConstraint(
            model_name='staffassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uq_staff_assignment'),
        ),
    ]
