# Generated by Django 5.2.17 on 2026-09-08 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('job_type', models.CharField(choices=[('products', 'Products'), ('prices', 'Prices'), ('inventory', 'Inventory'), ('customers', 'Customers')], max_length=24)),
                ('file_url', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('ready', 'Ready to apply'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, help_text='Row-level errors, downloadable', null=True)),
                ('dry_run', models.BooleanField(default=True, help_text='Validate without writing')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.JSONField()),
                ('value_type', models.CharField(default='string', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Exposed to the storefront')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setting',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('staff', 'Staff'), ('customer', 'Customer'), ('system', 'System'), ('webhook', 'Webhook')], default='system', max_length=16)),
                ('action', models.CharField(db_index=True, help_text='e.g. "order.status_changed"', max_length=60)),
                ('object_type', models.CharField(max_length=60)),
                ('object_id', models.BigIntegerField()),
                ('object_repr', models.CharField(blank=True, help_text='Human label at the time', max_length=200)),
                ('changes', models.JSONField(blank=True, help_text='{"status": ["paid", "processing"]}', null=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_id', models.UUIDField(blank=True, help_text='Ties to application logs', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['object_type', 'object_id', '-created_at'], name='idx_audit_object'), models.Index(fields=['actor', '-created_at'], name='idx_audit_actor')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120)),
                ('endpoint', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.SmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idempotency_key',
                'constraints': [models.UniqueConstraint(fields=('key', 'endpoint'), name='uq_idem')],
            },
        ),
    ]
